server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:../data/webchat.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

webchat:
  socketio:
    host: 0.0.0.0
    port: 9092
